### ISSUE TITLE
关于随堂练习资源的问题

### ISSUE THREAD

**Issue by octopusflyz** [UsanoCoCr/PKUICS#1]
您好，我是24年选ics的同学。你的题库中随堂练习的资料我比较想要（即标题为2021秋ics小班练习题），请问能否以邮件的形式打包发给我呢？github上好像打不开，把所有克隆下来又有点太大了┭┮﹏┭┮。我的邮箱octopusfly@stu.pku.edu.cn , 非常感谢！

**Comment by UsanoCoCr** [comment]
我已经发送了，同学可以查收一下
